const lastTeamEventsTypes = {
  GET_LAST_EVENT_START: "GET_LAST_EVENT_START",
  GET_LAST_EVENT_SUCCESS: "GET_LAST_EVENT_SUCCESS",
  GET_LAST_EVENT_ERROR: "GET_LAST_EVENT_ERROR"
};

export default lastTeamEventsTypes;
