const eventDetailsTypes = {
  GET_EVENT_DETAILS_START: "GET_EVENT_DETAILS_START",
  GET_EVENT_DETAILS_SUCCESS: "GET_EVENT_DETAILS_SUCCESS",
  GET_EVENT_DETAILS_ERROR: "GET_EVENT_DETAILS_ERROR"
};

export default eventDetailsTypes;
