const lastLeagueEventsTypes = {
  GET_LEAGUE_LAST_EVENTS_START: "GET_LEAGUE_LAST_EVENTS_START",
  GET_LEAGUE_LAST_EVENTS_SUCCESS: "GET_LEAGUE_LAST_EVENTS_SUCCESS",
  GET_LEAGUE_LAST_EVENTS_ERROR: "GET_LEAGUE_LAST_EVENTS_ERROR"
};

export default lastLeagueEventsTypes;
